- .github/workflows/build.yml
- Fixes #9 
- Fixed #10
**NB:** No changes required to any build scripts, dependencies or code.
> Adds support for Kernel 4.14 and 4.19 to CI

- libbpf/src/Makefile
- libbpf_0_0_1/src/Makefile
- library/Makefile
Fixes #16 
As explained in the issue, the size changes few Kb, so we are starting to work with static.
> Change elf linkage

- library/Makefile
- user/Makefile
> Fix rename of shared library

- Dockerfile.musl
> Fixes build issues on musl build env

- libbpf_0_0_1/src/libbpf.c
Actually fixes #23 (_finally_)
> Fixes builds for Kernel 4.14 on musl

- user/Makefile
Fixes #41 
This commit fix the compression of the final files.
>  Fix compress

- library/bpf_load.c
Fixes #50 
For more details, please, read the issue.
> update_library: Brings missing updates to the library

- .github/workflows/release.yml
See netdata/netdata#8075
See #11
> Sets up CI for publishing new releases to be consumed by NetData Installer

- user/process_user.c
> Fix a missing call to a function

- kernel/Makefile
- user/Makefile
We need to keep the developer mode running to have conditions to test,
but we cannot compress it, because it won't be delivered for  while
> Fix Makefile

- user/process_user.c
- user/process_user.h
The tester software was only return integer values that could not give additional information about possible errors, this commit fixes this problem
> Meaninful errors

- README.md
- kernel/Makefile
- kernel/latency_process_kern.c
- user/Makefile
- user/latency_process_user.c
- user/latency_test.c
When an eBPF program is loaded it brings some overhead to the system, this PR brings two software to test the latency on each function used.
> Latency on ebpf_program

- .github/workflows/build.yml
- kernel/process_kern.c
This PR brings percpu hash to kernel process
> PERCPU HASH to ebpf_program

- kernel/Makefile
- library/Makefile
- user/Makefile
> Fixed Kernel version detection we're building against

- .dockerfiles/patch_kernel.sh
- Dockerfile.glibc
> Added support for patching kernel sources before building

- .dockerfiles/build.sh
- .github/workflows/build.yml
- user/Makefile
> Package up the test binaires as part of the tarball package for artifacts

- Makefile
- build.sh
- tools/build-ebpf-kernel.sh
- tools/install.sh
- tools/uninstall.sh
- user/Makefile
- user/process_user.c
> Add various tools for debugging and e2e testing with different Kernel builds

- tools/check-kernel-config.sh
- user/process_user.c
Fixes #101 
Fixes #89 
This PR changes the script to also detect RH version and not only kernel version
> redhat_kernel_detection: Change script

- kernel/process_kern.c
- library/api.c
- library/bpf_load.c
Fixes #99 
This PR brings minor adjusts in the code necessaries to compile the eBPF programs on old kernel versions
> Old kernel support

- docs/Kernel-version-ebpf-program.md
- library/bpf_load.c
- library/trace_helpers.c
Fixes #128 
This PR brings the necessary changes for we reduce the number of libraries compiled.
> Kernel check during runtime

- docs/Compilation-as-normal-user.md
- kernel/Makefile
- library/Makefile
- user/Makefile
Fixes #131 
This PR brings the possibility to compile this repository as normal user.
> Compile repository as normal user.

- kernel/process_kern.c
Fixes #133 
This PR adjusts the index size to 64 bytes length.
> Increase index size

- library/bpf_load.c
Debian and Ubuntu have special ways to define their kernels, this PR brings the necessary adjusts to identify the correct kernel running on these distributions.
> Fix Debian family

- build.sh
- library/Makefile
- library/musl-gcc
- library/musl-gcc.specs
Bring shell script and spec file to compile repository.
> musl-gcc to kernel-collector

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile.static.generic
- build.sh
- library/Makefile
> Add support for building a `-static` artifact variant for Netdata static (kickstart-static64)

- kernel/network_viewer_kern.c
- kernel/process_kern.c
Fixes #157
This PR fixes the reported problem on #157 and it also fixes possible problems with process_kern.c.
> Synchronization

- kernel/network_viewer_kern.c
This PR fixes the field that we  are reading on this repo.
> Fix source port

- kernel/network_viewer_kern.c
This PR fixes the ebpf program load on kernel 4.14 and it also brings code optimization
> Fix load on kernel 4.14 and older

- kernel/network_viewer_kern.c
This PR brings the necessary changes for we add the following charts to `apps.plugin`:
- Calls for internal functions
- Package retransmission
> New ebpf charts

- .github/workflows/release.yml
This repo somehow got missed when I made a pass over all of our repos to fix this.
> Switch to new GHA environment variable syntax.

- Dockerfile.musl.generic
- Dockerfile.static.generic
> Bump Alpine image used for musl/static builds to 3.13.

- includes/netdata_ebpf.h
This PR fixes a code copied from kernel that was generating wrong eBPF programs.
> Fix code generation

- includes/netdata_ebpf.h
- includes/netdata_swap.h
- kernel/Makefile
- kernel/swap_kern.c
- rename_binaries.sh
Fixes #212 
This PR brings monitoring for functions used to access swap.
> Add swap monitoring

- .github/dependabot.yml
> Add dependabot config to update GitHub Actions and Dockerfiles.

- kernel/Makefile
- kernel/README.md
- kernel/xfs_kern.c
This eBPF program is adding a new eBPF program to monitor XFS filesystem.
I am also using this PR to bring some missing information for our documentation.
This PR as tested on:
|Slackware current | 5.12.9 |
|Manjaro  | 5.10.36-2 |
|Ubuntu 18.0.4  | 5.4.114 |
|Debian 10.9  | 4.19.171 |
|Ubuntu 18.0.4  | 4.15.18 |
|CentOS 7.9  | 3.10.0-1160.25 |
> XFS monitoring

- .github/workflows/build.yml
- .github/workflows/release.yml
> Fix dependabot

- .github/workflows/build.yml
- .github/workflows/release.yml
Needed for #255 to work correctly.
@thiagoftsm Feel free to just merge this once you approve it.
> Add handling of submodues to CI.

- includes/bpf_helpers.h
- includes/netdata_ebpf.h
- includes/netdata_oomkill.h
- kernel/Makefile
- kernel/README.md
- kernel/oomkill_kern.c
https://github.com/netdata/product/issues/2158
Tested with:
- TODO: Ubuntu 18.04 (Linux 4.15)
- Ubuntu 21.04 (Linux 5.11.0-31)
- TODO: CentOS 7 (Linux 3.10)
> OOM kill tracking

- .github/workflows/review.yml
Equivalent to https://github.com/netdata/netdata/pull/11553.
> Update automated review CI.

- includes/netdata_ebpf.h
- includes/netdata_mdflush.h
- kernel/Makefile
- kernel/README.md
- kernel/mdflush_kern.c
https://github.com/netdata/product/issues/1939
This collects flush counts per md unit. The name of the md device will be generated in the agent for display in charts as described in https://github.com/netdata/product/issues/1939#issuecomment-945445159 .
> md flush count collector

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- Dockerfile.musl.centos8
- Dockerfile.musl.generic
- Dockerfile.static.centos8
- Dockerfile.static.core
- Dockerfile.static.generic
This PR is bringing the following changes for this repo:
-  Update CODEOWNER
- Add template to create PRs.
- Update all docker images for latest `alpine` version
> Update dockerfile and github

- .github/workflows/release.yml
This also brings things in line with how we are handling releases now in the ebpf-co-re repo (Hooray for consistency!).
Merge it and create a release.
> Overhaul the release process to use modern actions workflows.

- .dockerfiles/change_libbpf.sh
- .github/PULL_REQUEST_TEMPLATE.md
This PR is simplifying developer contribution and also some tests that we run on specific distributions.
It is only necessary to check syntax.
> Modify GitHub files

- includes/netdata_vfs.h
1. Get binaries according your LIBC from [this](ADD ACTIONS LINK HERE) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| LINUX …
> Remove Header

- includes/netdata_socket.h
- kernel/Makefile
- kernel/network_viewer_kern.c
More details after tests.
1. Get binaries according your LIBC from [this](ADD ACTIONS LINK HERE) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
|--------------------|----------------|---------------|-------------|--------|-----------|----- …
> Network viewer

- kernel/network_viewer_kern.c
Small adjusts for previous PR.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8078637523) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
``` …
> Adjust timestamp

- includes/netdata_socket.h
- kernel/network_viewer_kern.c
Considering that the lowest level possible to collect is higher than what we have with `/proc`, this PR adds the TGID to structure to match what we have when work only with `/proc`.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8532199998) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | Parent |  All PIDs …
> Network Viewer (TGID)

- .github/workflows/release.yml
This PR addresses issues  related to release process.
```sh
```
```sh
``` …
> Update release process

- .github/workflows/release.yml
> Fix parameter position from previous PR

- .github/workflows/release.yml
> Adjust release according #386

- .github/workflows/release.yml
> Fix release process

- .github/workflows/release.yml
> Add checkout to release

- Dockerfile.musl.centos8
- Dockerfile.musl.centos9
- Dockerfile.musl.generic
- Dockerfile.musl.oracle8
- Dockerfile.static.centos8
- Dockerfile.static.centos9
- Dockerfile.static.generic
- Dockerfile.static.oracle8
Update Alpine version.
1.Check CI
| LINUX DISTRIBUION  | Bare metal/VM  | uname -r      |             |        |           |              |
> Update docker image

- .github/workflows/release.yml
Update CI.
```sh
```
```sh
```
|--------------------|----------------|---------------|-------------|--------|-----------|---------- …
> update_artifacts: Update download
