- kernel-check.sh
Exits with a non-zero exit code if the system's kernel doesn't support eBPF collector requirements.
This only issues warnings if the kernel version is too old, because RHEL/CentOS are questionable and use ancient kernel version numbers even though they have very new features.
This first checks if we're running on Linux, and bails early if we aren't.
Once checking the version and possibly issuing a warning, it then looks for the configuration in the following places, using the first it finds:
* `/proc/config.gz`: This is provided by the running kernel, but requires the kernel to have been configured to provide it (it may also need a module to be loaded, which we try to do if we can't find the file).
* `/lib/modules/${KERNEL_VERSION}/sources/.config`: This is provided by locally built …
> Add script to determine if the kernel has the needed options.

- .github/workflows/release.yml
See https://developer.github.com/v3/repos/releases/#get-the-latest-release
Releaseing non-full releases isn't that useful if I want to easily get the
latest release from ghte Github API which I'll need to use from the NetData
Installer.
> Sets prerelease to false

- kernel/Makefile
- user/Makefile
We won't deliver in the first version of eBPF collector the developer mode, so I am disabling its compilation.
> Disable dev mode

- user/process_user.c
This commit brings a missing check before to unmap the memory when there is an error.
> Check before unmap

- user/process_user.c
The use of perf events won't happen probably, so I am removing it from the tests.
> Remove calls to perf

- library/bpf_load.c
RedHat ported to the kernel on CentOS 7 an option inserted only on kernel 4.3
This commit brings this option back
> Remove ifdef to bring compatibility with RH

- kernel/process_kern.c
During the update of the index size, there was a variable that was not resized,
this PR fixes this
> Fix wrong variable length

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
This eepends on #135 (_and also contains its squashed commit to avoid merge conflicts_).
There is a [v0.0.7](https://github.com/prologic/netdata-kernel-collector/releases/tag/v0.0.7)
release on my [fork](https://github.com/prologic/netdata-kernel-collector)
which can be used to test/verify the changes in this PR are correct/valid.
> Update Release workflow to accomodate new packaging format for Netdata eBPF

- kernel/network_viewer_kern.c
- kernel/process_kern.c
Fixes #155 
Fixes #139 
This PR brings the necessary changes to allow ebpf.plugin to use the hash table to read and process information instead the proc filesystem.
We are setting only tgid as the index, because this is the value returned for `getpid()`.
The  `kprobe` to `try_to_wake_up` was added to be sure that we will have all the process running inside the hash table. We can add some statistical information on this PR in a near future.
> Adjusts on process ebpf program.

- kernel/netdata_ebpf.h
- kernel/process_kern.c
Fixes #159
Fixes #161 
Fixes #162 
Change value read to create charts that gives bytes information.
Bring a new variable and also comments the code that is creating problems.
> Fix values shown on charts when the collector is running in entry mode.

- kernel/network_viewer_kern.c
- kernel/process_kern.c
Fixes #166 
This PR is bringing the basis to read socket information.
We are splitting the probes for `tcp_sendmsg`, because when we read the argument given with `kretprobe` the number read does not match the bytes transmitted for the clients.
I am also using this PR to rename few hash tables that we access on user ring, because they had a name larger than the maximum number of bytes used for the command `bpftool`, this can be confirmed running the command `bpftool map show` . Considering that we will begin to use only libbpf to work direct with the eBPF programs, I am renaming it to avoid problems for us.
> Fix Network Viewer Variables

- kernel/network_viewer_kern.c
I will give the suggestion for we test this PR with the latest Netdata released, for we also test `libbpf`.
1 - Do download of the files from the Action https://github.com/netdata/kernel-collector/actions/runs/174873726.
2 - Stop your Netdata.
3 - Extract them and copy all `eBPF` programs to  `/usr/libexec/netdata/plugins.d`
4 - Start Netdata again
5 - Run `bpftool map show` and see the id of the map `tbl_conn_ipv4`
6 - Confirm that data was stored inside the table running : `bpftool map dump 3`, here I am assuming the result of the previous command was `3: per_cpu_hash tbl_conn_ipv4`.
I tested these `eBPF` programs on kernels `5.7.9`, `5.4.52`, `4.19.133`, `4.16.18` and `4.14.188`. and I observed that we always had data inside the tables, previous this PR I had data only on kernel …
> Fix socket read

- kernel/network_viewer_kern.c
With this PR Netdata will start to monitor connections accepted for specific ports.
This PR also fixes a data overwrite that we had when we were copying retransmission data.
> Fix inbound/outbound classification 

- kernel/network_viewer_kern.c
On `netdata/netdata` we moved the process management completely for the `ebpf_process.c` file, this means that this kprobe and the variable used to remove process are not more necessary on `socket` ebpf program.
I tested this PR on `Slackware current` and `Debian 10`, I used the following kernels to test it:
- 5.9.2
- 5.8.17
- 5.5.19
- 4.19 ( this is the official  Debian release)
- 4.16.18
- 4.15.18
- 4.14.203
I used the PR https://github.com/netdata/netdata/pull/10202 to test this, and my intention is to create a new release after to merge this PR that will be associated to the referred PR at `netdata/netdata`.
> Remove kprobe and variable

- kernel/network_viewer_kern.c
Fixes #178 
Fixes #176 
I tested this PR using the PR https://github.com/netdata/netdata/pull/10360 on the following kernels and distributions:
| Distribution | Kernel version |
|-----------------|---------------------|
|Slackware current | 5.9.11 |
|Slackware current | 5.8.18|
|Slackware current | 5.5.19|
|Slackware current | 5.4.83|
|Slackware current | 4.20.17|
|Slackware current | 4.19.161|
|Debian 10 | 4.19.132|
|Ubuntu 18.04 | 4.18.20(4.18.0-25.26)|
|Slackware current | 4.17.19|
|Ubuntu 18.04 | 4.15.18(4.15.0-123)|
|Centos 7.8 | 3.10.0-1160|
> Fix for old kernel

- kernel/network_viewer_kern.c
Bring back values for hidden network connection charts;
This PR was alread tested on the following systems using the PR https://github.com/netdata/netdata/pull/10442.
| Linux distribution | kernel version |
|-------------|-----------|
|Slackware current | 5.10.8 | 
|Slackware current | 5.4.85 |
| Ubuntu 20.04 | 5.4.0-60 |
| Ubuntu 18.04 | 5.4.0-60 |
| Ubuntu 18.04 | 4.18 |
> Network Traffic

- Makefile
- kernel/Makefile
- kernel/cachestat_kern.c
- kernel/netdata_ebpf.h
Fixes #190 
A complete explanation for the motive we are using these kprobes is given [here](http://www.brendangregg.com/blog/2014-12-31/linux-page-cache-hit-ratio.html )
This PR is bringing the necessary code to bring cache statistic to Netdata, it was tested on the following environments:
| Kernel version | distribution |
|-------------------|------------------|
| 5.10.13 | Slackware current |
| 5.9.16 | Slackware current |
| 5.7.19 | Slackware current |
| 5.4.95 | Slackware current |
| 5.4.78 | Ubuntu 20.04 |
| 5.4.78 | Ubuntu 18.04 |
| 4.20.17 | Slackware current |
| 4.19.171-2 | Debian 10.8 |
| 4.18.20 | Ubuntu 18.04 |
| 4.15.18 | Ubuntu 18.04 |
|3.10.0-1160.15.2.el7 |  CentOS 7.9.2009 |
> Add cachestat collector to ebpf programs

- .github/workflows/build.yml
- .github/workflows/release.yml
- kernel/process_kern.c
Fixes #199 
With the latest changes on Linux kernel, we need to change our internal code.
This PR was tested on `Slackware-current` running on kernel `5.11.2`.
> Fix kernel 5 11

- includes/netdata_dc.h
- includes/netdata_ebpf.h
- kernel/Makefile
- kernel/dc_kern.c
- rename_binaries.sh
Fixes #189 
This PR is bringing the logic behind [dcstat](https://github.com/iovisor/bcc/blob/master/tools/dcstat.py) to eBPF plugin. It was tested on : 
| Linux Distribution  | Kernel |
| ------------------------ | --------- | 
| Slackware Current | 5.11.2 |
| Slackware Current | 5.10.25 |
| Slackware Current | 5.4.95 |
| Ubuntu 18.04 | 4.15.0-136|
| CentOS | 3.10.0 |
> Ebpf Directory Cache

- kernel/cachestat_kern.c
- kernel/dc_kern.c
- kernel/process_kern.c
Fixes #210 
As described in the issue we need to reduce PID tables to reduce kernel memory usage, we will also give conditions for uses to set them according their necessity.
This simple reduction will save around 68% of memory we are using by default.
> Change default size

- kernel/dc_kern.c
When we merged directory cache, thanks the fact `cachestat` and `directory cache` monitor caches, there was an inversion of constants that we did not observe, because `cachestat` monitors more data than `directory cache`, so we are allocating more memory than necessary for directory cache. This PR brings the correct value for hash table.
> Change constant

- includes/netdata_ebpf.h
- includes/netdata_fs.h
- kernel/Makefile
- kernel/ext4_kern.c
Fixes #218 
We are monitoring the execution time to measure the latency.  All the buckets were defined using log2.
Some comments about the code to simplify reviewers life:
We are hard coding some values that we are considering safety, but remember it is possible to change these values before the eBPF program is loaded.
| Slackware Current | 5.12.0  |
| Slackware Current | 5.10.41 |
| Slackware Current | 5.9.16 |
| Ubuntu 18.0.4 | 5.4.106 |
| Manjaro 21.04 | 5.4.106 |
| Ubuntu 18.0.4 | 4.15.18 |
| Slackware Current | 4.14.231 |
| CentOS 7.9.2009 | 3.10.0-1160 |
> ext4 monitoring

- includes/netdata_fs.h
- kernel/ext4_kern.c
This PR is bringing two small fixes for EXT4:
- I am converting the temporary table from `ARRAY` to `HASH`  for we store all PIDs.
- I am reducing the number of elements for main table, because we had addresses never used.
| Slackware Current | 5.12.0  |
| Slackware Current | 5.10.41 |
| Slackware Current | 5.9.16 |
| Ubuntu 18.0.4 | 5.4.106 |
| Manjaro 21.04 | 5.4.106 |
| Ubuntu 18.0.4 | 4.15.18 |
| Slackware Current | 4.14.231 |
| CentOS 7.9.2009 | 3.10.0-1160 |
> Fix tables for ext4

- kernel/cachestat_kern.c
- kernel/dc_kern.c
- kernel/fdatasync_kern.c
- kernel/fsync_kern.c
- kernel/msync_kern.c
- kernel/process_kern.c
- kernel/socket_kern.c
- kernel/swap_kern.c
- kernel/sync_file_range_kern.c
- kernel/sync_kern.c
- kernel/syncfs_kern.c
- kernel/vfs_kern.c
We are storing sequential data in some tables, these tables do not need to be `HASH TABLES`, to speed up processing we are converting all of them to `ARRAYS`, and for functions with high frequency access, we are converting them to `PERCPU_ARRAYS`.
|Slackware current | 5.12.9 |
|Manjaro  | 5.10.36-2 |
|Ubuntu 18.0.4  | 5.4.114 |
|Debian 10.9  | 4.19.171 |
|Ubuntu 18.0.4  | 4.15.18 |
|CentOS 7.9  | 3.10.0-1160.25 |
> Convert hash table to array

- includes/netdata_ebpf.h
- kernel/cachestat_kern.c
- kernel/dc_kern.c
- kernel/process_kern.c
- kernel/swap_kern.c
- kernel/vfs_kern.c
This PR is adding a new table (array) that will allow us to reduce the memory usage for the minimum possible(4096B) when integration with `apps.plugin` is disabled. This is also a necessary step to integrate `eBPF.plugin` with `systemd`.
I am also using this PR to  remove a dead code from `process_ kern`.
I am not touching `socket`, because this specific eBPF program will have a PR for it. It will be an important part of the integration with `systemd` and I plan to split it in two different eBPF programs.
This PR was tested on :
|Slackware current | 5.12.10 |
|Manjaro  | 5.10.41-1 |
|Ubuntu 18.4 | 5.4.114|
|Ubuntu 18.0.4  | 4.15.18 
|Slackware current | 4.14.236 |
|CentOS 7.9  | 3.10.0-1160.25 |
> Add controller table and reduce memory usage

- includes/netdata_disk.h
- includes/netdata_ebpf.h
- kernel/Makefile
- kernel/disk_kern.c
This PR is bringing `tracepoints` for Netdata.
When it is merged, we will be able to monitor disk latency independent of the filesystem used on disk.
This PR was already tested on:
|Slackware current | 5.12.12 |
|Manjaro  | 5.10.42-1 |
|Ubuntu 18.0.4  | 5.4.114 |
|Debian 10.9  | 4.19.171 |
|Ubuntu 18.0.4  | 4.15.18 |
|Slackware current | 4.14.236 |
|CentOS 7.9  | 3.10.0-1160.25 |
> Disk latency

- kernel/disk_kern.c
After @vlvkobal to call attention [here](https://github.com/netdata/netdata/pull/11276#issuecomment-868283877) for a possible bad user experience with new eBPF charts, I am making this PR to avoid the chart separation. 
I  ran benchmarks with `ebpf_exporter` and [`iolantecy`](https://github.com/brendangregg/perf-tools/blob/master/iolatency), they showed me that the original charts were correct, but the user experience would not be good with them.
This decision was taken after to run different tests with all available options for the [tracepoint](https://elixir.bootlin.com/linux/latest/source/kernel/trace/blktrace.c#L1877). 
|Slackware current | 5.12.12 |
|Manjaro  | 5.10.42-1 |
|Ubuntu 18.0.4  | 5.4.114 |
|Debian 10.9  | …
> Centralize disk information

- kernel/Makefile
- kernel/README.md
- kernel/nfs_kern.c
This PR is bringing another filesystem monitoring.
Last PR we brought I missed documentation change, so I am also using this PR to bring this change.
| Slackware Current | 5.12.14 |
| Slackware Current | 5.4.114 |
| Slackware Current | 4.19.191 |
| Slackware Current | 4.14.238 |
> NFS monitoring

- kernel/Makefile
- kernel/README.md
- kernel/zfs_kern.c
Add new eBPF program to monitor latency for ZFS filesystem.
This PR was tested using `zfs 2.0.5` and `zfs 2.1.0` delivered by https://zfsonlinux.org/. For both ZFS versions, it was used kernel 5.12.15.
> ZFS monitoring

- kernel/Makefile
- kernel/btrfs_kern.c
- kernel/rename_binaries.sh
This PR is bringing the latest filesystem latency monitoring planned for this quarter.
This PR was already tested on:
| Slackware Current | 5.13.2  |
| Manajaro | 5.10.49 |
| Ubuntu 18.04 | 5.4.119 |
| Debian 10.10 | 4.19.171 |
| Ubuntu 18.04 | 4.15.18 |
| Slackware Current | 4.14.239 |
> eBPF btrfs

- includes/netdata_ebpf.h
- includes/netdata_mount.h
- kernel/Makefile
- kernel/README.md
- kernel/mount_kern.c
Bring monitoring for `mount` and `umount` syscalls.
This PR was tested on : 
| Slackware Current | 5.13.4  |
| Manajaro | 5.10.49 |
| Ubuntu 18.04 | 5.4.119 |
| Slackware Current | 4.14.239 |
> eBPF mount

- includes/bpf_helpers.h
- includes/netdata_ebpf.h
- includes/netdata_hardirq.h
- kernel/Makefile
- kernel/README.md
- kernel/hardirq_kern.c
https://github.com/netdata/product/issues/2155
> Hard IRQ latency tracking

- includes/netdata_ebpf.h
- includes/netdata_softirq.h
- kernel/Makefile
- kernel/README.md
- kernel/hardirq_kern.c
- kernel/softirq_kern.c
https://github.com/netdata/product/issues/2154
Tested with:
- Ubuntu 18.04 (Linux 4.15)
- Ubuntu 21.04 (Linux 5.11.0-31)
- CentOS 7 (Linux 3.10)
> Software IRQ latency tracking

- kernel/hardirq_kern.c
- kernel/softirq_kern.c
I did not realize that `valp` in the entrypoint functions was pointing to the *actual* ebpf map value, and that the update we do on it will persist for the value in the actual map.
This PR fixes it so we take this into account. Other collectors, including the swap one, do the same thing.
Tested with:
- Ubuntu 18.04 (Linux 4.15)
- Ubuntu 21.04 (Linux 5.11.0-31)
- CentOS 7 (Linux 3.10)
> Fix hardirq/softirq value init logic

- includes/netdata_ebpf.h
- includes/netdata_shm.h
- kernel/Makefile
- kernel/README.md
- kernel/shm_kern.c
https://github.com/netdata/product/issues/2159
Tested with:
- Ubuntu 21.04 (Linux 5.11.0-31)
- Ubuntu 18.04 (Linux 4.15)
- CentOS 7 (Linux 3.10)
> Shared memory syscall success/error tracking

- .gitmodules
- co-re/Makefile
- co-re/sync.bpf.c
- co-re/sync.c
- co-re/syncfs.bpf.c
- co-re/syncfs.c
- includes/netdata_tests.h
This PR is extending CO-RE bringing monitoring for 4 additional `sync` syscalls.
It also adds to `sync` tester the possibility to load either `kprobe` or `trampoline`.
1. Clone branch
2. Run `./tools/check-kernel-core.sh` to test your kernel. If you do not receive any warning, your host has support for BTF.
3. Install `bpftool` on your host.
4. Execute commands: `cd co-re && make`
5. Finally run: `./tests/sync`. If you do not have any warning, and you are able to see the following output:
```bash
bash-5.1# ./tests/sync --probe
__x64_sys_syncfs: probe loaded with success
__x64_sys_msync: probe loaded with success
__x64_sys_sync_file_range: probe loaded with success
__x64_sys_fsync: probe loaded with success
__x64_sys_fdatasync: probe loaded with success
bash-5.1# ./tests/sync --trampoline …
```
> Convert sync eBPF programs to CO-RE

- co-re/Makefile
- co-re/filesystem.bpf.c
- co-re/filesystem.c
- co-re/nfs.bpf.c
- includes/netdata_fs.h
This PR is converting all eBPF software that are delivered by Linux filesystem to new `libbpf`.
During development it was observed that neither Slackware nor Manjaro are compiling all filesystems with all options enabled, so the tester attached with this PR is using the more conservative approach. 
For you have a successful test, it is necessary to have filesystem modules loaded. It is not necessary to mount a partition with filesystem, you can load the module and in sequence to run the tester.
1 - Clone branch;
2 -  Go to `co-re` directory and run `make`;
3 - Load a module and run in sequence `./tests/filesystem --probe --btrfs`, changing the option for the filesystem
A complete example is given below:
```bash
bash-5.1# ./tests/filesystem --help
./tests/filesystem tests if it is possible …
```
> Filesystem CO-RE

- co-re/Makefile
- co-re/mount.bpf.c
- co-re/mount.c
- co-re/shm.bpf.c
- co-re/shm.c
- co-re/sync.bpf.c
- co-re/sync.c
- includes/netdata_tests.h
This PR is converting all remaining `syscall` to CO-RE. 
When trampolines are not available, we are converting direct to `kprobe`, but when we merge the code at `netdata/netdata` we will try monitoring according the following order:
1. Trampoline
2. Tracepoint
3. Kprobe
1. Clone branch;
2. Go to `co-re` directory and run `make`;
3. Run the following tests: 
```sh
bash-5.1# ./tests/sync --probe
__x64_sys_syncfs: probe loaded with success
__x64_sys_msync: probe loaded with success
__x64_sys_sync_file_range: probe loaded with success
__x64_sys_fsync: probe loaded with success
__x64_sys_fdatasync: probe loaded with success
__x64_sys_sync: probe loaded with success
bash-5.1# ./tests/sync --trampoline
Cannot find function __x64_sys_sync
__x64_sys_syncfs: probe loaded with success …
```
> Syscalls CO-RE

- co-re/Makefile
- co-re/process.bpf.c
- co-re/process.c
- co-re/shm.c
- includes/netdata_tests.h
This PR is bringing process monitoring using latest libbpf and CO-RE.
It also expands the monitored functions according the method used giving flexibility to `eBPF.plugin`.
1. Clone branch;
2. Go to `co-re` directory and run `make`;
3. Run the following tests: 
```sh
bash-5.1# ./tests/process --tramṕoline
./tests/process: unrecognized option '--tramṕoline'
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/process --tracepoint
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/process --probe
Process loaded with success
I'm a proud dad!
I'm the child.
Global data stored with success
Apps data stored with success …
```
> Process CO-RE

- .github/workflows/build.yml
- .gitignore
- co-re/Makefile
There are a lot of untracked files in the `libbpf` directory after CO-RE programs are built. The PR fixes that.
We are also doing a minor cleanup for `make` and `make clean` for CO-RE.
1.
```
cd libbpf
git clean -dxf
cd ../co-re
make
cd ../libbpf
git status
```
There shouldn't be any untracked files.
2.
```
cd co-re
make
make clean
```
You shouldn't see any errors and the output of `git clean -dxf` should be clean.
> Fix libbpf build

- Makefile
- README.md
- kernel-patches/README.md
- Fix of bash script for Ubuntu 20.04 support
- Fix of minor typos
- Added submodule initializing section into README.md
- Regular compiling process
- Reading README.md in the root and kernel-patches folder
> Fix bash script for Ubuntu 20.04 and typos

- co-re/Makefile
- co-re/fd.bpf.c
- co-re/fd.c
- co-re/mdflush.bpf.c
- co-re/mdflush.c
- includes/netdata_fd.h
This PR is converting more two legacy code to CO-RE.
1. Clone branch;
2. Go to `co-re` directory and run `make`;
3. Load `md` module or create MD array before to test `mdflush`.
4. Run the following tests: 
```sh
bash-5.1# ./tests/mdflush --probe
md_flush_request loaded with success
Global data stored with success
bash-5.1# ./tests/mdflush --tracepoint
This specific software does not have tracepoint, using kprobe instead
md_flush_request loaded with success
Global data stored with success
bash-5.1# ./tests/mdflush --trampoline
md_flush_request loaded with success
Global data stored with success
bash-5.1# ./tests/fd --probe
File descriptor loaded with success
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/fd --trampoline
File descriptor loaded with success …
```
> MD and File Descriptor (CO-RE)

- co-re/Makefile
- co-re/disk.bpf.c
- co-re/disk.c
- co-re/hardirq.bpf.c
- co-re/hardirq.c
- co-re/oomkill.bpf.c
- co-re/oomkill.c
- co-re/softirq.bpf.c
- co-re/softirq.c
- includes/netdata_disk.h
- includes/netdata_tests.h
This PR is converting the remaining eBPF.programs that uses only `tracepoints`
1. Clone this branch
2. Compile the `co-re` codes:
```sh
```
3. Run the following tests:
```sh
bash-5.1# ./tests/oomkill 
OOMkill loaded with success
Data stored with success
bash-5.1# ./tests/softirq 
Softirq loaded with success
Data stored with success
bash-5.1# ./tests/hardirq 
Hardirq loaded with success
Data stored with success
bash-5.1# ./tests/disk
Disk loaded with success
Data stored with success
```
This PR was already tested on:
| Slackware Current | 5.15.6  |
| Arch Linux        | 5.15.6  |
| CentOS 8.5.2111 | 4.18.0-348.2.1 |
> Tracepoints

- .dockerfiles/build_core.sh
- co-re/Makefile
- co-re/cachestat.c
- co-re/dc.bpf.c
- co-re/dc.c
- co-re/fd.bpf.c
- co-re/fd.c
- co-re/mount.c
- co-re/process.c
- co-re/shm.c
- co-re/swap.c
- co-re/sync.c
This PR is bringing following updates for codes  already merged:
1. Common error message when it is not possible to load eBPF programs;
2. Use `MY_LINUX_VERSION_CODE` instead `LINUX_VERSION_CODE`;
3. To prepare the integration with `eBPF.plugin` in `netdata/netdata`, we are also allowing other compilers to be used for final compilation steps.
4. This PR also update codes for file descriptor and directory cache
1. Clone branch
2. Go to directory `co-re` and run `make CC=clang`
3. Run the following tests:
```sh
bash-5.1# ./tests/dc --probe
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/dc --trampoline
Directory Cache loaded with success
Global data stored with success
Apps data stored with success
bash-5.1# ./tests/dc …
```
> Update merged code

- .gitignore
- Makefile
- co-re/Makefile
- kernel/Makefile
- kernel/tester.c
- kernel/tester.h
This PR is bringing a tester for our legacy code, the idea is to use this new software to test new PRs that we will bring before creating or to change threads in eBPF.plugin.
1. Clone this branch
2. Compile only the tester: 
```sh
```
3. Run few tests, for example,
```sh
bash-5.1# ./kernel/legacy_test --log-path tests.json --netdata-path /usr/libexec/netdata/plugins.d/ebpf.d/
bash-5.1# ./kernel/legacy_test --log-path tests.json --netdata-path /usr/libexec/netdata/plugins.d/ebpf.d/ --content
bash-5.1# ./kernel/legacy_test --log-path tests.json --netdata-path /usr/libexec/netdata/plugins.d/ebpf.d/ --content --iteration 2 --ext4
bash-5.1# ./kernel/legacy_test --load-binary rnetdata_ebpf_socket.5.15.o --content --iteration 2 --log-path tests.json 
bash-5.1$ grep Success tests_5_15.json | wc …
```
> Legacy tester

- .gitignore
- co-re/Makefile
- co-re/cachestat.c
- co-re/dc.c
- co-re/disk.c
- co-re/fd.c
- co-re/filesystem.c
- co-re/hardirq.c
- co-re/mdflush.c
- co-re/mount.c
- co-re/oomkill.c
- co-re/process.c
- co-re/shm.c
- co-re/socket.c
- co-re/softirq.c
- co-re/swap.c
- co-re/sync.c
- co-re/tests/run_tests.sh
- co-re/vfs.c
As  described in this [commit](https://lore.kernel.org/netdev/20210521234227.1286058-1-andrii@kernel.org/T/), when `libbpf 1.0` is  released, `libbpf` will work with `LIBBPF_STRICT_ALL`, we are adding a call for all functional testers that we have to be sure we are already prepared for changes that are coming. 
We are also adding a script that help us to test everything.
1. Clone branch
2. Go to `co-re` directory and compile: 
```sh
```
3. Enter to `tests` directory  inside `co-re` and run the script that we are adding with this PR.
```sh
``` 
4. Test at least one `fiilesystem` running manually:
```sh
``` 
Run the script [`tools/check-kernel-core.sh`](https://raw.githubusercontent.com/netdata/kernel-collector/master/tools/check-kernel-core.sh)
On kernel `5.16.x` this PR will have one …
> Compatibility test

- Makefile
- kernel/Makefile
This PR is adjusting our Makefiles to remove compilation of unnecessary binaries. Our users are already using Netdata without them. The steps to disable them were:
- Create PR #285 used to test the idea.
- Create PR https://github.com/netdata/netdata/pull/11992 that forced eBPF plugin to ignore these binaries.
- This PR that will remove them.
- A future PR that will be created after next code freeze ends, but this PR will be at `netdata/netdata`.
We are not removing the possibility to compile all binaries in more recent kernels, instead we are moving for another option called `dev`.
The next test describes what it was done to confirm that this PR  works:
1. Get all binaries compiled with a specific lib (I used GLIBC/GCC) from this …
> Reduce binaries

- .github/workflows/build.yml
- .github/workflows/release.yml
- co-re/cachestat.bpf.c
- co-re/cachestat.c
- kernel/Makefile
- kernel/cachestat_kern.c
- kernel/rename_binaries.sh
- kernel/tester.c
- kernel/tester.h
When kernel `5.16` was released, kernel team changed again the function used to mark a page cache as `dirty`. This generates the following error fixed with this PR: 
```conf
libbpf: kprobe perf_event_open() failed: No such file or directory
libbpf: prog 'netdata_set_page_dirty': failed to create kprobe '__set_page_dirty+0x0' perf event: No such file or directory
```
1. Clone this branch.
2. Access this [link](https://github.com/netdata/kernel-collector/actions/runs/1781430831) and get a file named artifacts-5.16.4-LIBC, where LIBC is the lib you have on your computer.  **This step is necessary only for hosts running kernel 5.16.x.**
3. Compile the legacy tester:
```sh
``` 
4. Run the following tests and verify that output is `Success`:
```sh
```
5. Go to `co-re` directory and compile the …
> Fix cachestat on kernels 5.16 and newer

- co-re/socket.bpf.c
- co-re/socket.c
- includes/netdata_socket.h
- kernel/socket_kern.c
As it was described in issue https://github.com/netdata/netdata/issues/12027 a specific `k(ret)probe`  was crashing an eBPF Virtual Machine and creating problems when eBPF.plugin was running on specific kernels. This PR is changing the socket internally to remove race condition that was present.
See `Additional information` for some results.
1. Get binaries from this [link](https://github.com/netdata/kernel-collector/actions/runs/1813038788) an extract them:
```sh
for i in `ls *.zip`; do unzip $i; rm .gitkeep ; rm $i; done
for i in `ls *.xz`; do tar -xf $i; rm $i* ; done
```
2. Compile the branch
```sh
```
3. Run legacy tester for entry and return codes:
```sh
```
4. Go to `co-re` directory and compile functional testers.
```sh
```
| Linux Distribution | kernel …
> Reorganize socket

- includes/netdata_socket.h
- kernel/socket_kern.c
This PR is bringing three new features for socket collector:
1. Monitoring for passive connections
2. Monitoring for active connections
3. Monitor for calls to `tcp_drop`.
1. Clone this Branch.
4. Get binaries compiled from this [link](https://github.com/netdata/kernel-collector/actions/runs/1954546015)
5. Extract the files in a specific directory:
```bash
```
6. Compile tester 
```bash
```
7. Run the tester for socket:
```bash
````
| Linux Distribution | kernel version | Socket log |
|--------------------|----------------|---------|
| Slackware Current  |     5.16.12    | [slackware_5_16.txt](https://github.com/netdata/kernel-collector/files/8211287/slackware_5_16.txt) |
| Arch Linux         |  5.16.11-arch1 | …
> Socket next steps

- includes/netdata_common.h
- kernel/cachestat_kern.c
- kernel/dc_kern.c
- kernel/process_kern.c
This PR is moving a function from `process` to another file, because it is useful for different eBPF programs.
It also brings changes for `directory cache` and `cachestat`.
1. Get files from [link](https://github.com/netdata/kernel-collector/actions/runs/2367320678) and store in a specific directory, for example, `~/PATH_TO_ARTIFACTS`
2. Extract the files running
```sh
for i in `ls *.zip`; do unzip $i; rm .gitkeep ; rm $i; done
for i in `ls *.xz`; do tar -xf $i; rm $i* ; done
```
3.  Compile current branch:
```sh
```
4. Run tests:
```sh
$ ./kernel/legacy_test --content --iteration 2 --process --cachestat --dc --netdata-path ../artifacts/ --log-path pid0.txt --pid 0
$ ./kernel/legacy_test --content --iteration 2 --process --cachestat --dc --netdata-path ../artifacts/ --log-path pid1.txt …
```
> Memory PID

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile.glibc.centos8
- Dockerfile.glibc.centos9
- Dockerfile.musl.centos8
- Dockerfile.musl.centos9
- Dockerfile.static.centos8
- Dockerfile.static.centos9
- kernel/Makefile
- kernel/rename_binaries.sh
- kernel/tester.c
- kernel/tester.h
This PR is adding a proper support for `RH 9.x` family.
1. Clone this branch
2. Get binaries from this [link](https://github.com/netdata/kernel-collector/actions/runs/2674172382) and save in a directory.
3. Extract binaries with the following commands:
```sh
for i in `ls *.zip`; do unzip $i; rm .gitkeep ; rm $i; done
for i in `ls *.xz`; do tar -xf $i; rm $i* ; done
```
4. Compile tester
```sh
```
5. Run tester with  new binaries:
```sh
```
Where `../artifacts` is the directory where I saved the binaries.
I do not see necessity to test in all available kernels, it is only necessary to test on latest `Alma/Rocky/RH` and one of the other kernels we support. This PR was tested on:
| Distribution | kernel version | Logs |
|-----------------|--------------------|---------|
|Slackware current | …
> Update Alma docker images

- kernel/btrfs_kern.c
- kernel/disk_kern.c
- kernel/ext4_kern.c
- kernel/hardirq_kern.c
- kernel/nfs_kern.c
- kernel/softirq_kern.c
- kernel/xfs_kern.c
- kernel/zfs_kern.c
This PR is currently blocked by https://github.com/netdata/kernel-collector/pull/309
This PR is bringing the latest `libbpf` for this repo and we are also adjusting our codes related to disk and filesystem giving conditions for them to be compiled on kernels newer or equal than `5.18.0`.
We are not modifying tester and github files, because current codes are working on different kernel versions, so we are only addressing the issue that compilation could not be completed.
1. Clone branch
2. Run the following commands:
```sh
```
3. Verify that compilation will end with success . 
Considering that main issue is created when we have kernel `5.18` or newer, I suggest to compile at least on a distribution that have it, for other kernels to take a look in CI results is enough.
This PR was tested …
> Update libbpf disk

- includes/netdata_tests.h
- kernel/dc_kern.c
- kernel/fd_kern.c
- kernel/shm_kern.c
- kernel/swap_kern.c
- kernel/vfs_kern.c
This PR is bringing modifications to monitor PID for File descriptors, Virtual File System, SWAP, and shared memory.
When this code is loaded by `ebpf.plugin`, the plugin must disable these threads by default, unless user enable them to avoid big overload on `release_task`.
This caution won't be necessary with `CO-RE` codes.
We also update our documentation with next PR at `netdata/netdata`.
1. Get binaries from [this](https://github.com/netdata/kernel-collector/actions/runs/2836755076) based in your `libc`  and store them inside a `directory`.
2.  Run the following commands to extract all files:
```sh
```
3. Run next commands:
```sh
```
| Linux …
> PID (other threads)

- kernel/socket_kern.c
This PR is bringing necessary changes in socket program allowing it to monitor PID better.
1. Get binaries from this [link](https://github.com/netdata/kernel-collector/actions/runs/2899854912) and save inside a `directory`.
2. Compile this branch: `make clean; make`
3. Run the following tests:
```sh
```
| Linux Distribution | kernel version | real parent | parent |  all |
|--------------------|----------------|---------|---------|---------|
| Slackware Current  |     5.19.2     | [slackware_5_19_pid0.txt](https://github.com/netdata/kernel-collector/files/9397716/slackware_5_19_pid0.txt) | [slackware_5_19_pid1.txt](https://github.com/netdata/kernel-collector/files/9397717/slackware_5_19_pid1.txt) | [slackware_5_19_pid2.txt](https://github.com/netdata/kernel-collector/ …
> Update socket to use latest functions

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR is updating `upoload-artifact` avoiding warnings during release.
1. Take a look on Actions linked to this PR, we should not have any warning.
>  Update `upload-artifact`

- kernel/Makefile
More details after tests....
1. Clone this branch and run:
```sh
```
2. Get binaries from this [link](https://github.com/netdata/kernel-collector/actions/runs/3751127189), and store inside a directory, for example, `artifacts`.
3. Extract them inside a directory:
```sh
```
4. Run the tests:
```sh
``` 
5.  Verify that everything ran as expected:
```sh
```
| Distribution | Kernel | Real Parent | Parent | All PIDs |
|-----------------|----------|------------------|----------|-------------|
| Slackware Current  |     5.19.17     |[slackware_pid0.txt](https://github.com/netdata/kernel-collector/files/10280004/slackware_pid0.txt)| …
> Sync libbpf

- .github/workflows/release.yml
Remove from release Oracle 8 that is not present in review CI.
Only check if github files are right
> Modify release process

- includes/netdata_hardirq.h
- kernel/hardirq_kern.c
More details after tests..
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/4622606766) link and extract them inside a `directory`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/11163014/artifacts.zip).
```sh
```
```sh
```
| Linux Distribution | kernel version | real parent | parent |  all |
|--------------------|----------------|-------------|--------|------|
| Slackware …
> Fix HARDIRQ on Debian family

- .github/workflows/review.yml
Replace the old deprecated set-output with ... >> $GITHUB_OUTPUT
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
TL;DR
> name: Save state
> run: echo "::save-state name={name}::{value}"
> 
> name: Set output
> run: echo "::set-output name={name}::{value}"
> 
> name: Save state
> run: echo "{name}={value}" >> $GITHUB_STATE
> 
> name: Set output
> run: echo "{name}={value}" >> $GITHUB_OUTPUT
Ref: https://github.com/netdata/infra/issues/3541
> Fix deprecated gha outputs

- includes/netdata_socket.h
- kernel/disk_kern.c
- kernel/socket_kern.c
This is the first PR modifying our eBPF programs to match product goals to have independent functions for all eBPF programs.
More details after tests.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/5514902934) link and extract them inside a `directory`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/12013800/artifacts.zip).
```sh
```
```sh
```
| Linux Distribution | kernel …
> Fix Disk and Socket changes

- .github/PULL_REQUEST_TEMPLATE.md
- kernel/socket_kern.c
This PR is updating libbpf locally.
More details after tests...
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/5532840058) link and extract them inside a `directory`.
You can also get everything for glibc  using [this](https://github.com/netdata/kernel-collector/files/12029994/artifacts.zip) link.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | Parent |  All | …
> Update libbpf version (1.2.2)

- kernel/socket_kern.c
Quick fix to update sockets already stored.
1. Get binaries according your LIBC from [this](ADD ACTIONS LINK HERE) link and extract them inside a `directory`.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | Parent |  All |
|--------------------|----------------|---------------|-------------|--------|------|
| LINUX DISTRIBUION  | Bare metal/VM …
> Missing variable set

- includes/netdata_common.h
- kernel/socket_kern.c
More details after final tests
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/5834973565) link and extract them inside a directory, for example: `../artifacts`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/12318150/artifacts.zip).
```sh
```
```sh
``` …
> Restrict loopback addr

- includes/netdata_socket.h
- kernel/socket_kern.c
After a talk with product team and to have a more clear picture about what we are going to deliver, we are creating this PR that will reduce I/O events in kernel ring.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/5965001864) link and extract them inside a directory, for example: `../artifacts`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/12432198/artifacts.zip).
```sh
```
```sh
```
This PR was …
> Speed socket

- includes/netdata_socket.h
- kernel/socket_kern.c
After our last demo, we discuss the basis to have our network viewer. This PR bringing necessary changes to have charts we discussed.
More details after tests..
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/6076592333) link and extract them inside a directory, for example: `../artifacts`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/12515981/artifacts.zip)
```sh
```
```sh
``` …
> Network Viewer basis

- includes/netdata_vfs.h
- kernel/tester_user.c
- kernel/vfs_kern.c
We are staring with this PR a new cycle to bring a new eBPF function for netdata, this time the focus is VFS that is also a function that consumes a lot of resources from host.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/6150176835) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| …
> VFS functions

- includes/netdata_vfs.h
- kernel/vfs_kern.c
Change  macro avoiding necessity to modify codes in `ebpf-co-re` repo.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/6164634902) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
``` …
> Remove Macro

- includes/netdata_process.h
- kernel/process_kern.c
While I was developing `ebpf_process` function it called my attention the number of  processes started by other processes. After to debug the event, I decided to also explicit TGID in this eBPF program, helping developers to understand better their own software.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/6292825746) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
4. Every test should ends with `Success`, …
> Explicit TGID

- includes/netdata_common.h
While compiling with clang 17.0.2 it was observed warnings, this PR fixes them.
1. Get binaries according your LIBC from [this](ADD ACTIONS LINK HERE) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
``` …
> Address Clang Warning

- includes/netdata_socket.h
- kernel/socket_kern.c
Add socket state.
1. Get binaries according your LIBC from [this](https://github.com/netdata/kernel-collector/actions/runs/7628979041) link and extract them inside a directory, for example: `../artifacts`.
You can also get everything for glibc [here](https://github.com/netdata/kernel-collector/files/14027613/artifacts.zip).
```sh
```
```sh
``` …
> Expand socket monitoring

- Dockerfile.musl.centos8
- Dockerfile.musl.centos9
- Dockerfile.musl.generic
- Dockerfile.musl.oracle8
- Dockerfile.static.centos8
- Dockerfile.static.centos9
- Dockerfile.static.generic
- Dockerfile.static.oracle8
This PR is bringing the same solution used with Oracle Dockerfiles to Alpine.
```sh
```
```sh
``` …
> Upgrade alpine

- includes/netdata_socket.h
- kernel/network_viewer_kern.c
We are using `inodes` in our network viewer, but this value is accessed inside kernel with a [lock](https://elixir.bootlin.com/linux/latest/source/net/core/sock.c#L2618), so we are adding a new variable to keep the pattern with the current kernel.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8073057107) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
3. Compile branch and run the following tests:
```sh
```
4. Every test should ends with `Success`, unless …
> Add timestamp to network viewer

- includes/netdata_socket.h
- kernel/network_viewer_kern.c
After to do some tests, we are modifying the binary to avoid necessity to parse any `/proc` file.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8134400052) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | …
> Discard completely necessity to parse /proc

- includes/netdata_socket.h
The usage of `linux/in6.h` created some issues to compile on more recent kernels, we are removing it and using a simplified version of the necessary structure
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | …
> fix issue with CO-RE codes

- kernel/network_viewer_kern.c
Add stats to hash table, to clean up them when users are not accessing the cloud dashboard.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8173561389) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | Parent | …
> Network Viewer Stats

- includes/netdata_socket.h
- kernel/network_viewer_kern.c
Address the request https://github.com/netdata/netdata/pull/17073#discussion_r1521243135.
```sh
```
```sh
``` …
> Reorganize structure

- kernel/network_viewer_kern.c
Address a comment in https://github.com/netdata/netdata/pull/17073.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8486565906) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
```
| Linux Distribution |   Environment  |Kernel Version | Real Parent | Parent |  All PIDs | Without …
> address_comments: Get different PIDs levels

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile.glibc.generic
Update `libbpf` and `Ubuntu` to generate new binaries.
1. Get binaries according to your C library from [this](https://github.com/netdata/kernel-collector/actions/runs/8923535477) link and extract them inside a directory, for example: `../artifacts`.
```sh
```
```sh
``` …
> Bump Libbpf and Ubuntu

- .github/workflows/release.yml
This PR is modifying final release. We are going to separate binaries, simplifying the final installation.
```sh
```
```sh
``` …
> Separate Binaries

- .github/workflows/release.yml
Isolate RH family binaries during release.
```sh
```
```sh
```
|--------------------|----------------|---------------|------------- …
> Split only RH

- .github/workflows/release.yml
> Add action

- includes/netdata_cache.h
- includes/netdata_dc.h
- includes/netdata_process.h
- includes/netdata_swap.h
- kernel/cachestat_kern.c
- kernel/dc_kern.c
- kernel/swap_kern.c
Adjust kernel-collector code improving memory usage in kernel ring.
```sh
```
```sh
``` …
> Improve eBPF memory usage

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
The artifacts produced by the Makefile are only used for development and for internal transfer of the build artifacts within the CI jobs, so the choice of compression doesn’t really matter much here.
XZ seems to be having issues inside the GHA runners for CI, so we need to use something else. Gzip is the most logical choice here since it should be everywhere.
n/a
n/a
> Switch from xz to gz for temporary artifacts.

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
After issues with compression, this PR tries only to pack files.
```sh
```
```sh
``` …
> Remove compression

- includes/netdata_process.h
- kernel/Makefile
- kernel/process_kern.c
- kernel/swap_kern.c
Kernel 6.16 also modified tracepoint used to monitor process creation.
```sh
```
```sh
``` …
> Modify Tracepoint

- includes/netdata_process.h
- kernel/Makefile
- kernel/process_kern.c
- kernel/rename_binaries.sh
- kernel/swap_kern.c
Adjust codes and rename scripts.
```sh
```
```sh
```
|--------------------|----------------|---------------|-------------|--------| …
> fix_processes: Change tracepoint structure used after kernel 6.16
